config/routes.rb
Rails.application.routes.draw do
  root 'foursquare#index'
  get 'search_foursquare', to: 'foursquare#search'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/foursquare_controller.rb
class FoursquareController < ApplicationController
  def index
    @form = FoursquareSearchForm.new
  end

  def search
    @form = FoursquareSearchForm.new(params[:foursquare_search_form])
    @results = @form.search_venues
    render :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/foursquare/index.html.erb
<div>
  <%= form_for @form, url: search_foursquare_path, method: :get do |f| %>
    <p>Near: <%= f.text_field :near %></p>
    <p>Lat: <%= f.text_field :lat %></p>
    <p>Lng: <%= f.text_field :lng %></p>
    <p>Query: <%= f.text_field :query %></p>
    <p>Venue Id: <%= f.text_field :venue_id %></p>
    <p><%= f.submit 'Search' %></p>
  <% end %>
</div>

<% if @results %>
  <%= debug @results.venues %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FoursquareApiRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>